name: Proje Kontrol Zinciri

# Bu robot ne zaman çalışsın?
on:
  push:
    branches: [ main, master ] # main veya master branch'ine her kod pushlandığında
  pull_request:
    branches: [ main, master ] # main'e birleştirilmek istenen her PR açıldığında

# Robot tam olarak hangi işleri yapacak?
jobs:
  kontrol-ve-test:
    runs-on: ubuntu-latest # GitHub bizim için arkada tertemiz bir Linux makine açacak

    steps:
# 1. Adım: Benim yazdığım kodları o Linux makinesinin içine çek
      - name: Kodları Klonla
        uses: actions/checkout@v4

# 2. Adım (YENİ): Git üzerinde olmayan gizli API dosyasını Secrets'tan oluştur
      - name: API Constants Dosyasını Oluştur
        run: |
          mkdir -p lib/core/consts
          echo "${{ secrets.API_CONSTANTS_CONTENT }}" | base64 --decode > lib/core/consts/apiConstants.dart

# 3. Adım: Linux makinesine Flutter/Dart ortamını kur
      - name: Flutter Ortamını Kur
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

# 4. Adım: Projenin paketlerini/bağımlılıklarını internetten indir
      - name: Paketleri Yükle
        run: flutter pub get

# 5. Adım: Koddaki yazım hatalarını kontrol et (İnfoları ölümcül sayma)
      - name: Kod Analizi Yap
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

# 6. Adım: CD Build apk
      - name: Build apk
        run: flutter build apk --debug

# 7. Adım: Upload github
      - name: Upload apk to github
        uses: actions/upload-artifact@v4
        with:
          name: muuv-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

# 0. Adım: Varsa projdeki testleri çalıştır
    #  - name: Testleri Koştur
    #    run: flutter test